### ISSUE TITLE
Turn all throw <string> into throw createError(...) with a standard baf-wallet error library  

### ISSUE THREAD

**Issue by Lev-Stambler** [bafnetwork/baf-wallet-v2#43]
- Create a baf-wallet error library
- Replace all throw 'string here' with throw createBafError(BafWalletError.ERROR_NAME) where BafWalletError is an enum and createBafError is a function

**Comment by Sladuca** [comment]
For instance, [this](https://github.com/bafnetwork/baf-wallet-v2/blob/ab01c254f913a4d452ed2e2ab1aba3508fe81860/apps/frontend/src/components/ApproveRedirect.svelte#L62)

**Comment by Sladuca** [comment]
closed by #49
