### ISSUE TITLE
Loading Wheels

### ISSUE THREAD

**Issue by Lev-Stambler** [bafnetwork/baf-wallet-v2#50]
Add loading wheels for login, init near account, delete near account, and for approve redirect

See this [loading npm library](https://www.npmjs.com/package/@tadashi/svelte-loading) or use one which you see fit.

Find the necessary bits of code in Auth.svelte, InitNearAccount.svelte, DeleteNearAccount.svelte, and ApproveRedirect.svelte

**Comment by Sladuca** [comment]
closed by #52
